### ISSUE TITLE
  File "/var/folders/l8/b9v1kgkd6nz9hl__21wh79hm0000gn/T/tmp0dmyw5s2/_tempconfig.py", line 37     bbox_loss=dict(type='IOU_Loss', iou_type='GIOU',loss_weight=0.05),             ^

### ISSUE THREAD

**Issue by albertyou2** [wuzhihao7788/yolodet-pytorch#20]
你好 @wuzhihao7788

我在mac上训练报错，

Traceback (most recent call last):
  File "tools/train.py", line 144, in <module>
    main()
  File "tools/train.py", line 69, in main
    cfg = Config.fromfile(args.config)
  File "/Users/youyin/Documents/人工智能研究项目/keypoint/yolodet-pytorch/yolodet/utils/config.py", line 173, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/Users/youyin/Documents/人工智能研究项目/keypoint/yolodet-pytorch/yolodet/utils/config.py", line 113, in _file2dict
    mod = import_module('_tempconfig')
  File "/Users/youyin/anaconda3/envs/yolodet/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/folders/l8/b9v1kgkd6nz9hl__21wh79hm0000gn/T/tmp0dmyw5s2/_tempconfig.py", line 37
    bbox_loss=dict(type='IOU_Loss', iou_type='GIOU',loss_weight=0.05),
            ^
SyntaxError: invalid syntax

**Comment by NongFu123** [comment]
检查一下这一句bbox_loss=dict(type='IOU_Loss', iou_type='GIOU',loss_weight=0.05),的上一句结尾是不是没加逗号

**Comment by dsp6414** [comment]
千万别轻易用中文目录与文件名，与国际接轨- ̗̀(๑ᵔ⌔ᵔ๑)。

**Comment by monoloxo** [comment]
我是在ubuntu18.04上做的，和你报的错几乎一样，请问你现在知道什么原因了吗？

**Comment by monoloxo** [comment]
我找到了，确实是yolov4_coco_100e.py中bbox那行的上一句的None后面没有逗号的原因。
