### ISSUE TITLE
dataloader 报错 

### ISSUE THREAD

**Issue by nkstatly** [wuzhihao7788/yolodet-pytorch#22]
RuntimeError: Caught RuntimeError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/root/liyang/yolodet-pytorch/yolodet/dataset/loader/build_dataloader.py", line 92, in collate
    clt[k] = torch.stack(v, 0)
RuntimeError: stack expects each tensor to be equal size, but got [3, 640, 640] at entry 0 and [3, 1280, 1280] at entry 6

是loader/build_dataloader.py 里面collate的问题？

**Comment by www516717402** [comment]
@nkstatly 两种方案，稍微修改一下即可
- 在collate里面先padding，然后在cat
- 提前处理好数据

**Comment by nkstatly** [comment]
> @nkstatly 两种方案，稍微修改一下即可
> 
> * 在collate里面先padding，然后在cat
> * 提前处理好数据

cfg中我注释了RandomAffine这一行，没有修改collate，能进行训练不报错
会不会是随机仿射变换时导致的

**Comment by wuzhihao7788** [comment]
能把你的cfg文件粘贴出来，我看一眼吗？

**Comment by nkstatly** [comment]
> 能把你的cfg文件粘贴出来，我看一眼吗？


[ppyolo_coco_100e.zip](https://github.com/wuzhihao7788/yolodet-pytorch/files/5884034/ppyolo_coco_100e.zip)
多谢了
