### ISSUE TITLE
Tuple Error when Data Loading

### ISSUE THREAD

**Issue by wenchima** [wuzhihao7788/yolodet-pytorch#30]
```
Traceback (most recent call last):
  File "tools/train.py", line 144, in <module>
    main()
  File "tools/train.py", line 140, in main
    train_detector(model,datasets,cfg,validate=args.validate,timestamp=timestamp,meta=meta)
  File "/home/wenchi/projects/yolodet-pytorch-2/yolodet/apis/train.py", line 161, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/wenchi/projects/yolodet-pytorch-2/yolodet/apis/runner.py", line 331, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wenchi/projects/yolodet-pytorch-2/yolodet/apis/runner.py", line 214, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/wenchi/miniconda3/envs/yolodet-2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/wenchi/miniconda3/envs/yolodet-2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/wenchi/miniconda3/envs/yolodet-2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/wenchi/miniconda3/envs/yolodet-2/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wenchi/miniconda3/envs/yolodet-2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wenchi/miniconda3/envs/yolodet-2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wenchi/miniconda3/envs/yolodet-2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wenchi/projects/yolodet-pytorch-2/yolodet/dataset/custom.py", line 112, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/wenchi/projects/yolodet-pytorch-2/yolodet/dataset/custom.py", line 106, in prepare_train_img
    return self.pipeline(results)
  File "/home/wenchi/projects/yolodet-pytorch-2/yolodet/dataset/pipelines/compose.py", line 47, in __call__
    data = t(data)
  File "/home/wenchi/projects/yolodet-pytorch-2/yolodet/dataset/pipelines/transforms.py", line 139, in __call__
    hsv[1] *= dsat
TypeError: 'tuple' object does not support item assignment
```

Hey guys, when I try to run the model on both COCO and my own custom dataset, I ran into the above error. I am sure that the annotation format is correct. Do you have some idea how to fix it? 

One more thing that I am not clear is the label.names. Could you show me the format of the label.names?  Could the above error caused by the label.names when doing data loading?

Thank you very much!

Wenchi

**Comment by wenchima** [comment]
I think the above problem is solved by just transforming hsv to array in the script of `yolodet/dataset/pipelines/transforms.py`. 
`hsv = np.asarray(hsv) `

**Comment by wenchima** [comment]
Now I can train the model but it keeps popping up the error below during the training process. 
```
error in modulated_deformable_im2col_cuda: no kernel image is available for execution on the device
error in modulated_deformable_col2im_coord_cuda: no kernel image is available for execution on the device
```
I guess the error should be due to the DFN setup and compile. The environment I am using is

```
>>> import torch
>>> torch.__version__
'1.9.1+cu111'
```
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
